### ISSUE TITLE
Tests fail in Node 8.x

### ISSUE THREAD

**Issue by palanik** [palanik/wrapi#9]
```
     Uncaught TypeError: Cannot read property 'toString' of undefined
      at matchStringOrRegexp (node_modules/nock/lib/scope.js:169:22)
      at checkHeaders (node_modules/nock/lib/scope.js:200:16)
      at Array.every (<anonymous>)
      at Object.match (node_modules/nock/lib/scope.js:203:25)
      at node_modules/nock/lib/request_overrider.js:240:26
      at Array.filter (<anonymous>)
      at end (node_modules/nock/lib/request_overrider.js:236:33)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:170:7)
      at Request.end (node_modules/request/request.js:1528:14)
      at end (node_modules/request/request.js:554:16)
      at Immediate._onImmediate (node_modules/request/request.js:581:7)
```

**Comment by palanik** [comment]
Apparently, it is an issue with [nock](https://www.npmjs.com/package/nock)
Refer [#925](https://github.com/node-nock/nock/issues/925)
